export const hanoiDistrictOption = [
  { id: 1, value: 'Quận Ba Đình', label: 'Quận Ba Đình' },
  { id: 2, value: 'Quận Hoàn Kiếm', label: 'Quận Hoàn Kiếm' },
  { id: 3, value: 'Quận Hai Bà Trưng', label: 'Quận Hai Bà Trưng' },
  { id: 4, value: 'Quận Đống Đa', label: 'Quận Đống Đa' },
  { id: 5, value: 'Quận Tây Hồ', label: 'Quận Tây Hồ' },
  { id: 6, value: 'Quận Cầu Giấy', label: 'Quận Cầu Giấy' },
  { id: 7, value: 'Quận Thanh Xuân', label: 'Quận Thanh Xuân' },
  { id: 8, value: 'Quận Hoàng Mai', label: 'Quận Hoàng Mai' },
  { id: 9, value: 'Quận Long Biên', label: 'Quận Long Biên' },
  { id: 10, value: 'Quận Bắc Từ Liêm', label: 'Quận Bắc Từ Liêm' },
  { id: 11, value: 'Quận Nam Từ Liêm', label: 'Quận Nam Từ Liêm' },
  { id: 12, value: 'Quận Hà Đông', label: 'Quận Hà Đông' },
  { id: 13, value: 'Huyện Ba Vì', label: 'Huyện Ba Vì' },
  { id: 14, value: 'Huyện Chương Mỹ', label: 'Huyện Chương Mỹ' },
  { id: 15, value: 'Huyện Đan Phượng', label: 'Huyện Đan Phượng' },
  { id: 16, value: 'Huyện Đông Anh', label: 'Huyện Đông Anh' },
  { id: 17, value: 'Huyện Gia Lâm', label: 'Huyện Gia Lâm' },
  { id: 18, value: 'Huyện Hoài Đức', label: 'Huyện Hoài Đức' },
  { id: 19, value: 'Huyện Mê Linh', label: 'Huyện Mê Linh' },
  { id: 20, value: 'Huyện Mỹ Đức', label: 'Huyện Mỹ Đức' },
  { id: 21, value: 'Huyện Phú Xuyên', label: 'Huyện Phú Xuyên' },
  { id: 22, value: 'Huyện Phúc Thọ', label: 'Huyện Phúc Thọ' },
  { id: 23, value: 'Huyện Quốc Oai', label: 'Huyện Quốc Oai' },
  { id: 24, value: 'Huyện Sóc Sơn', label: 'Huyện Sóc Sơn' },
  { id: 25, value: 'Huyện Thạch Thất', label: 'Huyện Thạch Thất' },
  { id: 26, value: 'Huyện Thanh Oai', label: 'Huyện Thanh Oai' },
  { id: 27, value: 'Huyện Thanh Trì', label: 'Huyện Thanh Trì' },
  { id: 28, value: 'Huyện Thường Tín', label: 'Huyện Thường Tín' },
  { id: 29, value: 'Huyện Ứng Hòa', label: 'Huyện Ứng Hòa' },
  { id: 30, value: 'Thị xã Sơn Tây', label: 'Thị xã Sơn Tây' }
]
