export const hochiminhDistrictOptions = [
  { id: 1, value: 'Quận 1', label: 'Quận 1' },
  { id: 2, value: 'Quận 2', label: 'Quận 2' },
  { id: 3, value: 'Quận 3', label: 'Quận 3' },
  { id: 4, value: 'Quận 4', label: 'Quận 4' },
  { id: 5, value: 'Quận 5', label: 'Quận 5' },
  { id: 6, value: 'Quận 6', label: 'Quận 6' },
  { id: 7, value: 'Quận 7', label: 'Quận 7' },
  { id: 8, value: 'Quận 8', label: 'Quận 8' },
  { id: 9, value: 'Quận 9', label: 'Quận 9' },
  { id: 10, value: 'Quận 10', label: 'Quận 10' },
  { id: 11, value: 'Quận 11', label: 'Quận 11' },
  { id: 12, value: 'Quận 12', label: 'Quận 12' },
  { id: 13, value: 'Quận Bình Tân', label: 'Quận Bình Tân' },
  { id: 14, value: 'Quận Bình Thạnh', label: 'Quận Bình Thạnh' },
  { id: 15, value: 'Quận Gò Vấp', label: 'Quận Gò Vấp' },
  { id: 16, value: 'Quận Phú Nhuận', label: 'Quận Phú Nhuận' },
  { id: 17, value: 'Quận Tân Bình', label: 'Quận Tân Bình' },
  { id: 18, value: 'Quận Tân Phú', label: 'Quận Tân Phú' },
  { id: 19, value: 'Quận Thủ Đức', label: 'Quận Thủ Đức' },
  { id: 20, value: 'Huyện Bình Chánh', label: 'Huyện Bình Chánh' },
  { id: 21, value: 'Huyện Cần Giờ', label: 'Huyện Cần Giờ' },
  { id: 22, value: 'Huyện Củ Chi', label: 'Huyện Củ Chi' },
  { id: 23, value: 'Huyện Hóc Môn', label: 'Huyện Hóc Môn' },
  { id: 24, value: 'Huyện Nhà Bè', label: 'Huyện Nhà Bè' }
]
