export const citiesOption = [
  { id: 1, value: 'Hà Nội', label: 'Hà Nội' },
  { id: 2, value: 'Hồ Chí Minh', label: 'Hồ Chí Minh' },
  { id: 4, value: 'Huế', label: 'Huế' },
  { id: 3, value: 'Hải Phòng', label: 'Hải Phòng' },
  { id: 6, value: 'Đà Nẵng', label: 'Đà Nẵng' },
  { id: 5, value: 'Cần Thơ', label: 'Cần Thơ' }
  // { id: 7, value: 'Tỉnh Bắc Kạn', label: 'Tỉnh Bắc Kạn' },
  // { id: 8, value: 'Tỉnh Bắc Ninh', label: 'Tỉnh Bắc Ninh' },
  // { id: 9, value: 'Tỉnh Cao Bằng', label: 'Tỉnh Cao Bằng' },
  // { id: 10, value: 'Tỉnh Hà Giang', label: 'Tỉnh Hà Giang' },
  // { id: 11, value: 'Tỉnh Hải Dương', label: 'Tỉnh Hải Dương' },
  // { id: 12, value: 'Tỉnh Hòa Bình', label: 'Tỉnh Hòa Bình' },
  // { id: 13, value: 'Tỉnh Lạng Sơn', label: 'Tỉnh Lạng Sơn' },
  // { id: 14, value: 'Tỉnh Lào Cai', label: 'Tỉnh Lào Cai' },
  // { id: 15, value: 'Tỉnh Phú Thọ', label: 'Tỉnh Phú Thọ' },
  // { id: 16, value: 'Tỉnh Quảng Ninh', label: 'Tỉnh Quảng Ninh' },
  // { id: 17, value: 'Tỉnh Sơn La', label: 'Tỉnh Sơn La' },
  // { id: 18, value: 'Tỉnh Tuyên Quang', label: 'Tỉnh Tuyên Quang' },
  // { id: 19, value: 'Tỉnh Vĩnh Phúc', label: 'Tỉnh Vĩnh Phúc' },
  // { id: 20, value: 'Tỉnh Yên Bái', label: 'Tỉnh Yên Bái' },
  // { id: 21, value: 'Tỉnh Điện Biên', label: 'Tỉnh Điện Biên' },
  // { id: 22, value: 'Tỉnh Lai Châu', label: 'Tỉnh Lai Châu' },
  // { id: 23, value: 'Tỉnh Sơn La', label: 'Tỉnh Sơn La' },
  // { id: 24, value: 'Tỉnh Hòa Bình', label: 'Tỉnh Hòa Bình' },
  // { id: 25, value: 'Tỉnh Tuyên Quang', label: 'Tỉnh Tuyên Quang' },
  // { id: 26, value: 'Tỉnh Hà Tĩnh', label: 'Tỉnh Hà Tĩnh' },
  // { id: 27, value: 'Tỉnh Hải Dương', label: 'Tỉnh Hải Dương' },
  // { id: 28, value: 'Tỉnh Quảng Bình', label: 'Tỉnh Quảng Bình' },
  // { id: 29, value: 'Tỉnh Quảng Trị', label: 'Tỉnh Quảng Trị' },
  // { id: 30, value: 'Tỉnh Thừa Thiên Huế', label: 'Tỉnh Thừa Thiên Huế' },
  // { id: 32, value: 'Tỉnh Quảng Nam', label: 'Tỉnh Quảng Nam' },
  // { id: 33, value: 'Tỉnh Quảng Ngãi', label: 'Tỉnh Quảng Ngãi' },
  // { id: 34, value: 'Tỉnh Bình Định', label: 'Tỉnh Bình Định' },
  // { id: 35, value: 'Tỉnh Phú Yên', label: 'Tỉnh Phú Yên' },
  // { id: 36, value: 'Tỉnh Khánh Hòa', label: 'Tỉnh Khánh Hòa' },
  // { id: 37, value: 'Tỉnh Ninh Thuận', label: 'Tỉnh Ninh Thuận' },
  // { id: 38, value: 'Tỉnh Bình Thuận', label: 'Tỉnh Bình Thuận' },
  // { id: 39, value: 'Tỉnh Kon Tum', label: 'Tỉnh Kon Tum' },
  // { id: 40, value: 'Tỉnh Gia Lai', label: 'Tỉnh Gia Lai' },
  // { id: 41, value: 'Tỉnh Đắk Lắk', label: 'Tỉnh Đắk Lắk' },
  // { id: 42, value: 'Tỉnh Đắk Nông', label: 'Tỉnh Đắk Nông' },
  // { id: 43, value: 'Tỉnh Lâm Đồng', label: 'Tỉnh Lâm Đồng' },
  // { id: 44, value: 'Tỉnh Bình Dương', label: 'Tỉnh Bình Dương' },
  // { id: 45, value: 'Tỉnh Bình Phước', label: 'Tỉnh Bình Phước' },
  // { id: 46, value: 'Tỉnh Bà Rịa – Vũng Tàu', label: 'Tỉnh Bà Rịa – Vũng Tàu' },
  // { id: 47, value: 'Tỉnh Đồng Nai', label: 'Tỉnh Đồng Nai' },
  // { id: 48, value: 'Tỉnh Tây Ninh', label: 'Tỉnh Tây Ninh' },
  // { id: 49, value: 'Tỉnh Long An', label: 'Tỉnh Long An' },
  // { id: 50, value: 'Tỉnh Tiền Giang', label: 'Tỉnh Tiền Giang' },
  // { id: 51, value: 'Tỉnh Bến Tre', label: 'Tỉnh Bến Tre' },
  // { id: 52, value: 'Tỉnh Trà Vinh', label: 'Tỉnh Trà Vinh' },
  // { id: 53, value: 'Tỉnh Vĩnh Long', label: 'Tỉnh Vĩnh Long' },
  // { id: 54, value: 'Tỉnh Đồng Tháp', label: 'Tỉnh Đồng Tháp' },
  // { id: 55, value: 'Tỉnh Sóc Trăng', label: 'Tỉnh Sóc Trăng' },
  // { id: 56, value: 'Tỉnh Hậu Giang', label: 'Tỉnh Hậu Giang' },
  // { id: 57, value: 'Tỉnh Kiên Giang', label: 'Tỉnh Kiên Giang' },
  // { id: 58, value: 'Tỉnh Cà Mau', label: 'Tỉnh Cà Mau' },
  // { id: 59, value: 'Tỉnh An Giang', label: 'Tỉnh An Giang' },
  // { id: 60, value: 'Tỉnh Bạc Liêu', label: 'Tỉnh Bạc Liêu' },
  // { id: 61, value: 'Tỉnh Bến Tre', label: 'Tỉnh Bến Tre' },
  // { id: 62, value: 'Tỉnh Cà Mau', label: 'Tỉnh Cà Mau' },
  // { id: 63, value: 'Tỉnh Cần Thơ', label: 'Tỉnh Cần Thơ' },
  // { id: 64, value: 'Tỉnh Đồng Tháp', label: 'Tỉnh Đồng Tháp' },
  // { id: 65, value: 'Tỉnh Hậu Giang', label: 'Tỉnh Hậu Giang' },
  // { id: 66, value: 'Tỉnh Kiên Giang', label: 'Tỉnh Kiên Giang' },
  // { id: 67, value: 'Tỉnh Cà Mau', label: 'Tỉnh Cà Mau' }
]
